FROM golang:1.24.9-bookworm AS build
RUN git clone --depth 1 --branch RELEASE.2025-10-15T17-29-55Z https://github.com/minio/minio.git /src
WORKDIR /src
RUN --mount=type=cache,target=/root/.cache/go-build --mount=type=cache,target=/go/pkg/mod CGO_ENABLED=0 go build -p 2 -trimpath -o /minio-server . && /minio-server --version
FROM debian:bookworm-slim
RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates curl && curl --version && rm -rf /var/lib/apt/lists/*
COPY --from=build /minio-server /usr/local/bin/minio
RUN minio --version
ENTRYPOINT ["minio"]
